services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.mongodb:/data/db

  my-frontend:
    image: my-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
      no_cache: true
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"

  my-backend:
    image: my-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.development
      no_cache: true
    restart: always
    volumes:
      - ./backend:/backend
    depends_on:
      - mongodb

  my-nginx:
    image: my-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      no_cache: true
    depends_on:
      - mongodb
      - my-frontend
      - my-backend
    ports:
      - "80:80"
