# Use the official Bun image as the base image
FROM oven/bun:latest

# Set the working directory
WORKDIR /backend

# Copy package.json and bun.lockb files
COPY package.json bun.lockb ./

# Install dependencies
RUN bun install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Start the application
CMD ["bun", "dev"]