FROM oven/bun:latest

WORKDIR /backend

RUN touch /bin/run-backend.sh
RUN chmod +x /bin/run-backend.sh
RUN echo "bun install --no-save;" \
         "bun dev --host" \ >> /bin/run-backend.sh

EXPOSE 8080

CMD ["/bin/run-backend.sh"]